"""Application-wide constants for validation and data handling."""

# Maximum number of characters allowed for user provided text fields.
MAX_DESCRIPTION_LENGTH = 1000
MAX_RECIPIENT_NAME_LENGTH = 255
MAX_RECIPIENT_ADDRESS_LENGTH = 500
MAX_CATEGORY_NAME_LENGTH = 255

# User-related field length limits.
MAX_USERNAME_LENGTH = 50
MAX_USER_NAME_LENGTH = 100
MAX_USER_PHONE_LENGTH = 30
MAX_USER_ROAD_LENGTH = 200
MAX_USER_HOUSE_NUMBER_LENGTH = 20
MAX_USER_REGION_LENGTH = 100
MAX_USER_POSTAL_LENGTH = 20
MAX_USER_CITY_LENGTH = 100
MAX_USER_STATE_LENGTH = 100
